'use client';

import { useEffect, useMemo, useRef, useState, useId } from 'react';
import Link from 'next/link';
import { ArrowDownLeft, ArrowUpRight, ArrowRight, Boxes, Check, ChevronRight, CircleDollarSign, Clock3, ExternalLink, LayoutDashboard, LayoutGrid, List, LockKeyhole, LogOut, Moon, Pin, RefreshCw, Search, ShieldCheck, Sun, Target, Wallet, X } from 'lucide-react';
import { tradeDate, newestTradeFirst, tradeSource } from '@/lib/trades';
import type { Asset, AssetClass, Currency, PortfolioData, Snapshot } from '@/lib/types';
import { assetPnl, assetPriceHistory, comparableSnapshots, convert, filterHistory, historyChange, mergePortfolio, periodChange, summarize, type PeriodChange } from '@/lib/calculations';

const sections = [{ id: 'overview', href: '/', name: 'Обзор', icon: LayoutDashboard }, { id: 'cs2', href: '/cs2', name: 'Counter-Strike 2', icon: Boxes }, { id: 'sandbox', href: '/sandbox', name: 'Sandbox', icon: Wallet }, { id: 'crypto', href: '/crypto', name: 'Криптовалюты', icon: CircleDollarSign }] as const;
const classNames: Record<AssetClass, string> = { cs2: 'Counter-Strike 2', sandbox: 'Sandbox', crypto: 'Криптовалюты' };
const money = (value: number | null | undefined, currency: Currency = 'RUB', digits = 0) => value == null ? '—' : new Intl.NumberFormat('ru-RU', { style: 'currency', currency, minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value);
const number = (value: number, digits = 2) => new Intl.NumberFormat('ru-RU', { maximumFractionDigits: digits }).format(value);
const pct = (value: number | null) => value === null ? '—' : `${value > 0 ? '+' : ''}${number(value, 1)}%`;
const signed = (value: number | null, currency: Currency = 'RUB', digits = 0) => value === null ? '—' : `${value > 0 ? '+' : value < 0 ? '−' : ''}${money(Math.abs(value), currency, digits)}`;
const color = (value: number | null) => value === null ? '' : value >= 0 ? 'positive' : 'negative';
const time = (at: string | null | undefined, full = false) => at && Number.isFinite(Date.parse(at)) ? new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short', ...(full ? { year: 'numeric' as const } : {}), hour: '2-digit', minute: '2-digit', timeZone: 'Europe/Astrakhan' }).format(new Date(at)) : 'Дата неизвестна';
const stale = (at: string | null) => !at || !Number.isFinite(Date.parse(at)) || Date.now() - Date.parse(at) > 3600000;
const horizons = [{ days: 1, label: '24 часа' }, { days: 7, label: '7 дней' }, { days: 30, label: '30 дней' }] as const;
const changeStatus = (change: PeriodChange) => change.status === 'stale' ? 'Котировка устарела' : change.status === 'incomparable' ? 'Состав изменился' : 'Недостаточно данных';
const changeDescription = (change: PeriodChange) => change.status === 'ready' ? `${time(change.from, true)} → ${time(change.to, true)}` : change.status === 'incomparable' ? 'Изменились остатки или покрытие оценки; изменение цены нельзя выделить.' : change.status === 'stale' ? 'Для сравнения нужна свежая котировка. Старые значения сохранены с прежними датами.' : 'Нужны реальные наблюдения в начале и конце периода. Более короткая история не подменяет полный период.';
const feeText = (t: Asset['trades'][number]) => t.feeUnknown ? 'Неизвестна' : t.feeQuantity !== undefined ? `${number(t.feeQuantity, 8)} ${t.feeCurrency || ''}` : t.feeType === 'PERCENT' ? `${number(t.fee, 6)}%` : t.fee ? `${number(t.fee, 8)} ${t.feeCurrency || 'ед. источника'}` : '0';
type Options = { pinned?: boolean; note?: string; target?: number };

function AssetImage({ asset }: { asset: Asset }) {
  const [failed, setFailed] = useState(false);
  return <span className={`asset-image ${asset.class}`}>{asset.icon && !failed ? <img src={asset.icon} alt="" loading="lazy" onError={() => setFailed(true)} /> : asset.symbol ? <b>{asset.symbol.slice(0, 2)}</b> : <Boxes size={22}/>}</span>;
}

function ChangeCell({ change, currency, unitPrice = false }: { change: PeriodChange; currency: Currency; unitPrice?: boolean }) {
  return <span className={`change-cell ${color(change.absolute)}`} title={changeDescription(change)}>{change.status === 'ready' ? <>{pct(change.percent)}<small>{signed(change.absolute, currency, unitPrice && currency === 'USD' ? 6 : 2)}</small></> : <><span className="change-missing">—</span><small>{changeStatus(change)}</small></>}</span>;
}

function PeriodSummary({ snapshots, currency, unitPrice = false }: { snapshots: Snapshot[]; currency: Currency; unitPrice?: boolean }) {
  const changes = horizons.map(horizon => ({ ...horizon, change: periodChange(snapshots, horizon.days) }));
  return <div className="period-summary"><span className="period-summary-label">{unitPrice ? 'Изменение цены одной единицы' : 'Изменение рыночной оценки'} · {currency === 'RUB' ? '₽' : '$'}</span><div className="period-metrics" aria-label={unitPrice ? 'Изменение цены за единицу' : 'Изменение стоимости портфеля'}>{changes.map(({ days, label, change }) => <div className="period-metric" key={days}><span>{label}</span><ChangeCell change={change} currency={currency} unitPrice={unitPrice}/></div>)}</div><details className="period-explanation"><summary>Как рассчитана динамика</summary><p>{unitPrice ? 'Сравниваются цены одной единицы; количество в портфеле на этот расчёт не влияет.' : 'Сравнение доступно при одинаковых остатках и покрытии оценки во всех снимках интервала.'} База — последнее реальное наблюдение до начала периода: не старше 1 часа для суток, 2 часов для недели и 24 часов для месяца. Даты ниже показывают фактический интервал.</p>{changes.map(({ days, label, change }) => <div key={days}><strong>{label}</strong><span>{changeDescription(change)}</span></div>)}</details></div>;
}

function HistoryChart({ snapshots, currency, title, unitPrice = false }: { snapshots: Snapshot[]; currency: Currency; title: string; unitPrice?: boolean }) {
  const [period, setPeriod] = useState('week');
  const [hover, setHover] = useState<number | null>(null);
  const [showCost, setShowCost] = useState(false);
  const uid = useId().replace(/:/g, '');
  const data = useMemo(() => filterHistory(snapshots, period), [snapshots, period]);
  const first = data[0], last = data.at(-1), change = historyChange(data);
  const activeHover = hover !== null && hover < data.length ? hover : null;
  const vals = data.flatMap(d => !showCost || d.cost === null ? [d.value] : [d.value, d.cost]);
  const digits = unitPrice ? currency === 'USD' ? 6 : 2 : 0;
  const lo = Math.min(...vals), hi = Math.max(...vals), pad = Math.max((hi - lo) * .15, hi * .015, unitPrice ? currency === 'USD' ? .000001 : .01 : 1);
  const min = Math.max(0, lo - pad), max = hi + pad;
  const start = first ? Date.parse(first.at) : 0, end = last ? Date.parse(last.at) : 1;
  const x = (s: Snapshot) => 76 + (Date.parse(s.at) - start) / Math.max(end - start, 1) * 784;
  const y = (v: number) => 242 - (v - min) / Math.max(max - min, Number.EPSILON) * 206;
  const line = (key: 'value' | 'cost') => data.map((d, i) => d[key] === null ? '' : `${i === 0 || data[i - 1][key] === null || (key === 'value' ? !comparableSnapshots(d, data[i - 1]) : d.costCoverageKey !== data[i - 1].costCoverageKey) || Date.parse(d.at) - Date.parse(data[i - 1].at) > 3 * 86400000 ? 'M' : 'L'}${x(d)},${y(d[key]!)}`).join(' ');
  const highlighted = activeHover === null ? last : data[activeHover];
  return <div className="history-content"><PeriodSummary snapshots={snapshots} currency={currency} unitPrice={unitPrice}/><div className="chart-toolbar"><div><span className="chart-value">{money(last?.value, currency, digits)}</span><span className={color(change)}>{signed(change, currency, unitPrice ? digits : 2)} <small>за доступный интервал</small></span></div><div className="periods" aria-label="Период графика">{[['day', 'День'], ['week', 'Неделя'], ['month', 'Месяц'], ['year', 'Год'], ['all', 'Всё']].map(([id, text]) => <button key={id} aria-pressed={period === id} onClick={() => { setPeriod(id); setHover(null); }}>{text}</button>)}</div></div>
    {last && !last.complete && <p className="source-footnote">График оценённой части: {last.pricedCount ?? 'часть'} из {last.totalCount ?? 'всех'} позиций. Изменение состава оценённых активов разрывает линию.</p>}
    {last?.costComplete === false && <p className="source-footnote">Себестоимость известна для {last.knownCostCount} из {last.totalCount} позиций; её график показывает только эту часть.</p>}
    {data.length > 1 && change === null && <p className="source-footnote">Остатки или покрытие оценки менялись либо не записаны в старых снимках. Изменение стоимости за интервал несопоставимо; реальные значения показаны отдельными точками.</p>}
    {data.length > 0 ? <><div className="chart-plot" role="group" aria-label={title} tabIndex={0} onKeyDown={e => { if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { e.preventDefault(); setHover(current => Math.min(data.length - 1, Math.max(0, (current ?? data.length - 1) + (e.key === 'ArrowRight' ? 1 : -1)))); } }}>
      <svg viewBox="0 0 900 280" role="img" aria-label={`${title}, ${data.length} реальных снимков, ${currency}`} onMouseLeave={() => setHover(null)} onMouseMove={e => { const rect = e.currentTarget.getBoundingClientRect(); const target = start + ((e.clientX - rect.left) / rect.width * 900 - 76) / 784 * (end - start); let closest = 0; data.forEach((d, i) => { if (Math.abs(Date.parse(d.at) - target) < Math.abs(Date.parse(data[closest].at) - target)) closest = i; }); setHover(closest); }}>
        <defs><linearGradient id={`fill-${uid}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--accent)" stopOpacity=".16"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs>
        {[0, 1, 2, 3].map(i => <g key={i}><line x1="76" x2="860" y1={36 + i * 206 / 3} y2={36 + i * 206 / 3} className="grid-line"/><text x="65" y={40 + i * 206 / 3} textAnchor="end" className="axis-label">{number(Math.max(0, max - i * (max - min) / 3), digits)}{currency === 'RUB' ? ' ₽' : ' $'}</text></g>)}
        {data.length > 1 && <><path d={line('value')} className="value-line"/>{showCost && <path d={line('cost')} className="cost-line"/>}</>}
        {data.map((d, i) => <circle key={d.at} cx={data.length === 1 ? 468 : x(d)} cy={y(d.value)} r={i === hover || data.length === 1 ? 5 : 2.3} className="chart-point"><title>{`${time(d.at, true)}: ${money(d.value, currency, unitPrice ? digits : 2)}`}</title></circle>)}
        {showCost && data.length === 1 && last?.cost !== null && <circle cx={468} cy={y(last!.cost!)} r={4} fill="#94a4b5"><title>{`Себестоимость: ${money(last!.cost, currency, digits)}`}</title></circle>}
        {data.length > 1 && [0, .5, 1].map((ratio, i) => <text key={i} x={76 + ratio * 784} y="272" textAnchor={i === 0 ? 'start' : i === 2 ? 'end' : 'middle'} className="axis-label">{new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short', ...(end - start < 86400000 ? { hour: '2-digit' as const, minute: '2-digit' as const } : {}), timeZone: 'Europe/Astrakhan' }).format(new Date(start + ratio * (end - start)))}</text>)}
        {activeHover !== null && data.length > 1 && <line x1={x(data[activeHover])} x2={x(data[activeHover])} y1="30" y2="242" className="hover-line"/>}
      </svg><div className="chart-readout" aria-live="polite"><span>{time(highlighted?.at, true)}</span><strong>{money(highlighted?.value, currency, unitPrice ? digits : 2)}</strong></div>
    </div><div className="chart-caption"><span><i/> {unitPrice ? 'Цена за единицу' : 'Рыночная оценка'}</span>{data.some(d => d.cost !== null) && <button className="cost-toggle" aria-pressed={showCost} onClick={() => setShowCost(!showCost)}><i className="cost-dot"/> {showCost ? "Скрыть себестоимость" : "Показать себестоимость"}</button>}<span>{data.length} снимков · {data.length === 1 ? 'Линия появится после следующего сопоставимого снимка' : `История с ${time(first.at, true)}`}</span></div></> : <div className="chart-empty"><Clock3 size={28}/><strong>За этот период пока нет снимков</strong><p>{snapshots.length ? `Доступная история начинается ${time(snapshots[0].at, true)}. Выберите «Всё».` : 'Цены будут сохраняться при обновлениях. Покупки доступны в истории операций.'}</p></div>}
    {data.length > 0 && <details className="chart-data"><summary>Значения графика</summary><div className="compact-table"><table><thead><tr><th>Дата снимка</th><th>{unitPrice ? 'Цена единицы' : 'Оценка'}</th>{!unitPrice && <th>Себестоимость</th>}</tr></thead><tbody>{data.map(d => <tr key={d.at}><td>{time(d.at, true)}</td><td>{money(d.value, currency, unitPrice ? digits : 2)}{!d.complete && <small>{d.pricedCount}/{d.totalCount} позиций</small>}</td>{!unitPrice && <td>{money(d.cost, currency, 2)}{d.costComplete === false && <small>Частично: {d.knownCostCount}/{d.totalCount}</small>}</td>}</tr>)}</tbody></table></div></details>}
  </div>;
}

export default function Dashboard({ initialData, section }: { initialData: PortfolioData; section: 'overview' | AssetClass }) {
  const [data, setData] = useState(initialData), [theme, setTheme] = useState('light'), [view, setView] = useState('table');
  const [options, setOptions] = useState<Record<string, Options>>({}), [ready, setReady] = useState(false);
  const [query, setQuery] = useState(''), [sort, setSort] = useState('value'), [category, setCategory] = useState('Все');
  const [selected, setSelected] = useState<string | null>(null), [tab, setTab] = useState('assets');
  const [chartSource, setChartSource] = useState<AssetClass | 'overview'>(section);
  const [limit, setLimit] = useState(16), [refreshing, setRefreshing] = useState(false), [refreshError, setRefreshError] = useState('');
  const closeRef = useRef<HTMLButtonElement>(null), priorFocus = useRef<HTMLElement | null>(null), dialogRef = useRef<HTMLElement>(null);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem('tracker.v2.preferences') || '{}'); setTheme(saved.theme || 'light'); setView(saved.view || (window.innerWidth < 700 ? 'grid' : 'table')); const old = JSON.parse(localStorage.getItem('tracker.item-options.v1') || '{}'); const migrated = Object.fromEntries(Object.entries(old).map(([name, value]) => { const o = value as Options; return [`cs2:${name}`, { ...o, target: o.target === undefined ? undefined : o.target / 100 }]; })); setOptions({ ...migrated, ...JSON.parse(localStorage.getItem('tracker.v2.options') || '{}') }); } catch { /* optional preferences */ } setReady(true); }, []);
  useEffect(() => { if (ready) try { localStorage.setItem('tracker.v2.preferences', JSON.stringify({ theme, view })); localStorage.setItem('tracker.v2.options', JSON.stringify(options)); } catch { /* browser may disallow storage */ } }, [theme, view, options, ready]);
  useEffect(() => { setLimit(16); }, [query, category, sort]);
  useEffect(() => { if (!selected) return; priorFocus.current = document.activeElement as HTMLElement; closeRef.current?.focus(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; const key = (event: KeyboardEvent) => { if (event.key === 'Escape') setSelected(null); if (event.key === 'Tab') { const elements = dialogRef.current?.querySelectorAll<HTMLElement>('button, a[href], input, textarea, summary, [tabindex="0"]'); if (!elements?.length) return; const first = elements[0], last = elements[elements.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', key); return () => { document.body.style.overflow = previous; document.removeEventListener('keydown', key); priorFocus.current?.focus(); }; }, [selected]);
  async function refresh() { setRefreshing(true); setRefreshError(''); try { const response = await fetch('/api/portfolio', { cache: 'no-store' }); if (response.status === 401) { window.location.assign('/login'); return; } if (!response.ok) throw new Error(); const next = await response.json(); if (!Array.isArray(next.assets)) throw new Error(); setData(current => mergePortfolio(current, next)); } catch { setRefreshError('Обновление не удалось. Показан последний доступный снимок.'); } finally { setRefreshing(false); } }
  useEffect(() => { const timer = setInterval(() => { void refresh(); }, 300000); return () => clearInterval(timer); }, []);
  const active = data.assets.filter(a => a.quantity > 0), assets = section === 'overview' ? active : active.filter(a => a.class === section);
  const allAssets = section === 'overview' ? data.assets : data.assets.filter(a => a.class === section);
  const currency: Currency = section === 'crypto' ? 'USD' : 'RUB';
  const priceHistories = useMemo(() => new Map(data.assets.map(asset => [asset.id, assetPriceHistory(asset, data.history[asset.class])])), [data.assets, data.history]);
  const priceChanges = useMemo(() => new Map(data.assets.map(asset => [asset.id, horizons.map(horizon => periodChange(priceHistories.get(asset.id) ?? [], horizon.days))])), [data.assets, priceHistories]);
  const totals = summarize(assets, data.usdRub, section === 'crypto');
  const salesResult = summarize(allAssets, data.usdRub, section === 'crypto').realized;
  const classTotals = (id: AssetClass) => summarize(active.filter(a => a.class === id), data.usdRub);
  const knownPriceCost = (asset: Asset) => asset.price !== null && asset.cost !== null ? asset.price * asset.quantity - asset.cost : null;
  const assetValue = (a: Asset) => section === 'crypto' ? a.price === null ? null : a.price * a.quantity : convert(a.price === null ? null : a.price * a.quantity, a.currency, data.usdRub);
  const filtered = assets.filter(a => (category === 'Все' || a.category === category) && `${a.name} ${a.symbol || ''}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => Boolean(options[a.id]?.pinned) !== Boolean(options[b.id]?.pinned) ? options[a.id]?.pinned ? -1 : 1 : sort === 'name' ? a.name.localeCompare(b.name) : sort === 'quantity' ? b.quantity - a.quantity : sort.startsWith('change') ? (priceChanges.get(b.id)?.[Number(sort.slice(-1))].percent ?? -Infinity) - (priceChanges.get(a.id)?.[Number(sort.slice(-1))].percent ?? -Infinity) : sort === 'pnl' ? (assetPnl(b, data.usdRub, section === "crypto") ?? -Infinity) - (assetPnl(a, data.usdRub, section === "crypto") ?? -Infinity) : (assetValue(b) ?? -Infinity) - (assetValue(a) ?? -Infinity));
  const chosen = data.assets.find(a => a.id === selected), chosenOptions = chosen ? options[chosen.id] || {} : {};
  const updateOption = (update: Options) => chosen && setOptions(current => ({ ...current, [chosen.id]: { ...current[chosen.id], ...update } }));
  const transactions = allAssets.flatMap(a => a.trades.map((trade, index) => ({ ...trade, asset: a, index }))).sort(newestTradeFirst);
  const coverage = totals.total ? Math.round(totals.priced / totals.total * 100) : 0;
  const totalValue = (classTotals('cs2').value ?? 0) + (classTotals('sandbox').value ?? 0) + (classTotals('crypto').value ?? 0);
  const chartCurrency: Currency = chartSource === 'crypto' ? 'USD' : 'RUB';
  const snapshots = chartSource === 'overview' ? data.combinedHistory : data.history[chartSource];
  const sourceIssues = (['cs2', 'sandbox', 'crypto'] as AssetClass[]).filter(id => (section === 'overview' || section === id) && (data.sources[id].error || data.sources[id].deliveryError));
  async function logout() { const response = await fetch('/api/auth/logout', { method: 'POST' }); if (response.ok) window.location.assign('/login'); else setRefreshError('Выход не выполнен. Повторите попытку.'); }
  return <div className={`tracker theme-${theme}`}>
    <aside className="sidebar"><Link href="/" className="brand"><span className="brand-icon"><Wallet size={22}/></span><span>tracker<span className="brand-period">.</span><small>Личный капитал</small></span></Link><div className="nav-heading">ПОРТФЕЛЬ</div><nav aria-label="Разделы портфеля">{sections.map(({ id, href, name, icon: Icon }) => <Link key={id} href={href} className={`nav-label ${section === id ? "active" : ""}`} aria-current={section === id ? "page" : undefined}><Icon size={19}/><span>{name}</span>{id !== 'overview' && <small>{active.filter(a => a.class === id).length}</small>}</Link>)}</nav><div className="sidebar-bottom"><div className="private-label"><ShieldCheck size={18}/><span>Личный кабинет<small>Доступ только для admin</small></span></div><button onClick={logout}><LogOut size={17}/> Выйти</button></div></aside>
    <main className="workspace"><header className="workspace-top"><div><span className="breadcrumb">Мои активы</span><ChevronRight size={14}/><strong>{section === 'overview' ? 'Обзор портфеля' : classNames[section]}</strong></div><div className="top-controls"><button className="icon-button mobile-logout" aria-label="Выйти" onClick={logout}><LogOut size={17}/></button><span className="private-chip"><LockKeyhole size={12}/> Вход защищён</span><button className="icon-button" aria-label={theme === 'light' ? 'Тёмная тема' : 'Светлая тема'} onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>{theme === 'light' ? <Moon size={18}/> : <Sun size={18}/>}</button><button className="refresh-button" aria-label={refreshing ? "Обновление портфеля" : "Обновить портфель"} onClick={refresh} disabled={refreshing}><RefreshCw size={15} className={refreshing ? 'spinning' : ''}/><span>{refreshing ? 'Обновление' : 'Обновить'}</span></button></div></header>
    <div className="page-content"><section className="page-heading"><div><div className="eyebrow">{section === 'overview' ? 'ОБЩАЯ КАРТИНА' : 'МОИ АКТИВЫ'}</div><h1>{section === 'overview' ? 'Портфель' : classNames[section]}</h1><p>{section === 'overview' ? 'Весь капитал — от игровых предметов до криптовалют.' : section === 'crypto' ? 'Монеты, докупки и результат в долларах.' : 'Инвентарь, стоимость покупки и оценка Steam в рублях.'}</p></div><div className="date-chip"><Clock3 size={15}/>{new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Europe/Astrakhan' }).format(new Date())}</div></section>
    {refreshError && <div className="notice" role="status">{refreshError}</div>}
    {sourceIssues.length > 0 && <details className="notice source-issues"><summary>Есть проблемы с обновлением: {sourceIssues.map(id => classNames[id]).join(', ')}. Показаны последние сохранённые котировки.</summary>{sourceIssues.map(id => <div key={id}><strong>{classNames[id]}</strong>{data.sources[id].error && <p>{data.sources[id].error}{data.sources[id].attemptedAt && ` Последняя попытка источника: ${time(data.sources[id].attemptedAt)}.`}</p>}{data.sources[id].deliveryError && <p>{data.sources[id].deliveryError}</p>}</div>)}</details>}
    <section className="capital-grid"><div className="capital-card"><div className="capital-top"><span>{totals.complete ? 'Стоимость портфеля' : 'Оценённая часть портфеля'}</span><span className="coverage-chip"><Check size={12}/> {totals.priced}/{totals.total} с ценой</span></div><div className="capital-number">{money(totals.value, currency)}</div><div className="capital-bottom"><span className={`pnl-tag ${color(totals.pnl)}`}>{pct(totals.roi)}</span><span>к известной себестоимости</span><div className="capital-art"><span/><span/><span/><span/><span/><span/><span/></div></div></div>
    <div className="metric-stack"><div className="stat-card"><span>Вложено в открытые позиции</span><strong>{money(totals.cost, currency)}</strong><small>{totals.knownCost < totals.total ? `${totals.knownCost}/${totals.total} с известной себестоимостью` : section === 'overview' ? 'Крипта пересчитана по курсу оценки' : 'Остаточная себестоимость'}</small></div><div className="stat-card"><span>Нереализованный результат</span><strong className={color(totals.pnl)}>{signed(totals.pnl, currency)}</strong><small>Для позиций с ценой и себестоимостью</small></div></div><div className="metric-stack"><div className="stat-card"><span>Результат продаж</span><strong className={color(salesResult)}>{signed(salesResult, currency)}</strong><small>По известным операциям</small></div><div className="stat-card"><span>Активов в портфеле</span><strong>{assets.length}<small> позиций</small></strong><small>{section === 'crypto' ? 'Количество монет — в таблице' : section === 'overview' ? 'Три класса активов' : `${number(assets.reduce((s, a) => s + a.quantity, 0), 0)} предметов`}</small></div></div></section>
    <section className="analytics-grid"><div className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">ДИНАМИКА</span><h2>Стоимость во времени</h2></div><span className="currency-chip">{chartCurrency === 'RUB' ? '₽ · рубли' : '$ · доллары'}</span></div>{section === 'overview' && <div className="chart-source-tabs" aria-label="Активы на графике">{[['overview', 'Общий'], ['cs2', 'CS2'], ['sandbox', 'Sandbox'], ['crypto', 'Крипта']].map(([id, label]) => <button key={id} aria-pressed={chartSource === id} onClick={() => setChartSource(id as typeof chartSource)}>{label}</button>)}</div>}<HistoryChart key={chartSource} title={chartSource === 'overview' ? 'Общая стоимость' : classNames[chartSource]} snapshots={snapshots} currency={chartCurrency}/>{chartSource === 'overview' && <p className="source-footnote">Общая история начинается с подключения всех трёх портфелей. Старые котировки Sandbox не восстановлены.</p>}</div>
    <div className="panel allocation-panel"><div className="panel-heading"><div><span className="eyebrow">СОСТАВ</span><h2>{section === 'overview' ? 'Распределение капитала' : 'Качество оценки'}</h2></div></div>{section === 'overview' ? <><div className="allocation-bar">{(['cs2', 'sandbox', 'crypto'] as AssetClass[]).map(id => <span key={id} className={id} style={{ width: `${totalValue ? (classTotals(id).value ?? 0) / totalValue * 100 : 0}%` }}/>)}</div>{(['cs2', 'sandbox', 'crypto'] as AssetClass[]).map(id => { const s = classTotals(id); return <Link href={`/${id}`} className="allocation-row" key={id}><span className={`class-marker ${id}`}><Boxes size={17}/></span><span>{classNames[id]}<small>{active.filter(a => a.class === id).length} позиций · {s.priced}/{s.total} с ценой</small></span><strong>{money(s.value)}<small>{totalValue ? s.value === null ? '—' : number(s.value / totalValue * 100, 1) : 0}%</small></strong><ChevronRight size={15}/></Link>; })}</> : <><div className="coverage-display"><strong>{coverage}<span>%</span></strong><p>позиций имеют котировку</p></div><div className="quality-row"><span>Цена известна</span><strong>{totals.priced} из {totals.total}</strong></div><div className="quality-row"><span>Себестоимость известна</span><strong>{totals.knownCost} из {totals.total}</strong></div><div className="quality-row"><span>Котировки старше часа</span><strong>{assets.filter(a => stale(a.updatedAt)).length}</strong></div></>}<div className="fx-note"><CircleDollarSign size={16}/><span>1 USD ≈ {money(data.usdRub, 'RUB', 2)}<small>{data.fxSource} · {time(data.fxUpdatedAt)}</small></span></div></div></section>
    {section === 'overview' && <section className="panel portfolio-summary"><div className="panel-heading"><div><span className="eyebrow">СВОДНЫЙ УЧЁТ</span><h2>Все портфели</h2></div><span className="muted">Стоимость в ₽ · Динамика в валюте источника</span></div><div className="table-scroll"><table><thead><tr><th>Портфель</th><th>Вложено</th><th>Стоимость</th><th>Результат</th>{horizons.map(horizon => <th key={horizon.days}>Оценка · {horizon.label}</th>)}<th>Источник / дата</th><th/></tr></thead><tbody>{(['cs2', 'sandbox', 'crypto'] as AssetClass[]).map(id => { const s = classTotals(id); return <tr key={id}><td><Link href={`/${id}`} className="portfolio-name"><span className={`class-marker ${id}`}><Boxes size={18}/></span>{classNames[id]}</Link></td><td>{money(s.cost)}{s.knownCost < s.total && <small>Частично: {s.knownCost}/{s.total}</small>}</td><td><strong>{money(s.value)}</strong><small>{s.complete ? 'Все позиции оценены' : `${s.priced}/${s.total} позиций`}</small></td><td className={color(s.pnl)}>{signed(s.pnl)}<small>{pct(s.roi)}</small></td>{horizons.map(horizon => <td key={horizon.days}><ChangeCell change={periodChange(data.history[id], horizon.days)} currency={id === 'crypto' ? 'USD' : 'RUB'}/></td>)}<td><span className={`freshness ${stale(data.sources[id].at) ? 'old' : ''}`}><i/>{data.sources[id].name}</span><small>{time(data.sources[id].at)}</small></td><td><Link aria-label={`Открыть ${classNames[id]}`} href={`/${id}`}><ArrowUpRight size={18}/></Link></td></tr>; })}</tbody></table></div></section>}
    {section === 'sandbox' && <div className="verification-card"><ShieldCheck size={22}/><div><strong>Инвентарь сверен со Steam</strong><p>{time(data.verifiedAt, true)} · {assets.length} позиций · {number(assets.reduce((sum, a) => sum + a.quantity, 0), 0)} предметов</p><details><summary>Уточнения учёта</summary>{data.sandboxNotes.map(note => <p key={note}>{note}</p>)}</details></div>{data.verifiedInventoryUrl && <a href={data.verifiedInventoryUrl} target="_blank" rel="noreferrer">Инвентарь <ExternalLink size={14}/></a>}</div>}
    <section className="panel assets-panel"><div className="panel-heading"><div><span className="eyebrow">ДЕТАЛИ ПОРТФЕЛЯ</span><h2>{tab === 'assets' ? 'Активы' : 'История операций'} <span className="count-chip">{tab === 'assets' ? assets.length : transactions.length}</span></h2></div><div className="tab-buttons"><button aria-pressed={tab === 'assets'} onClick={() => setTab('assets')}>Активы</button><button aria-pressed={tab === 'trades'} onClick={() => setTab('trades')}>Операции</button></div></div>
    {tab === 'assets' ? <><p className="asset-dynamics-note">Динамика — изменение цены одной единицы за 24 часа, 7 и 30 дней. Покупки и продажи меняют остаток, но не процент цены. «—» означает отсутствие сопоставимой истории.</p><div className="asset-toolbar"><label className="search-box"><Search size={16}/><input aria-label="Поиск активов" placeholder="Найти предмет или монету…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Категория активов" value={category} onChange={e => setCategory(e.target.value)}>{['Все', ...new Set(assets.map(a => a.category))].map(c => <option key={c}>{c}</option>)}</select><select aria-label="Сортировка активов" value={sort} onChange={e => setSort(e.target.value)}><option value="value">По стоимости</option><option value="pnl">По результату</option><option value="name">По названию</option><option value="quantity">По количеству</option><option value="change0">Изменение за 24 часа</option><option value="change1">Изменение за 7 дней</option><option value="change2">Изменение за 30 дней</option></select><div className="view-switch"><button aria-label="Табличный вид" aria-pressed={view === 'table'} onClick={() => setView('table')}><List size={17}/></button><button aria-label="Плиточный вид" aria-pressed={view === 'grid'} onClick={() => setView('grid')}><LayoutGrid size={17}/></button></div></div>
      {filtered.length === 0 ? <div className="empty-list">Подходящих активов нет. Измените поиск или категорию.</div> : view === 'table' ? <div className="table-scroll"><table className="asset-table"><thead><tr><th>Актив</th><th>Количество</th><th>Средняя покупка</th><th>Текущая цена</th>{horizons.map(horizon => <th key={horizon.days}>Цена · {horizon.label}</th>)}<th>Вложено</th><th>{section === 'overview' ? 'Стоимость, ₽' : 'Стоимость'}</th><th>Результат</th><th/></tr></thead><tbody>{filtered.slice(0, limit).map(a => { const p = knownPriceCost(a); return <tr key={a.id}><td><button className="asset-name" title={a.name} onClick={() => setSelected(a.id)}><AssetImage asset={a}/><span>{a.symbol || a.name}{options[a.id]?.pinned && <Pin size={12}/>}<small>{section === 'overview' ? `${classNames[a.class]} · ` : ''}{a.symbol ? a.name : a.category}</small></span></button></td><td>{number(a.quantity, a.class === "crypto" ? 6 : 2)}</td><td>{money(a.averageBuyPrice, a.currency, a.currency === 'USD' ? 5 : 2)}</td><td>{money(a.price, a.currency, a.currency === 'USD' ? 6 : 2)}<small className={stale(a.updatedAt) ? 'stale-text' : ''}>{time(a.updatedAt)}</small></td>{priceChanges.get(a.id)?.map((change, i) => <td key={horizons[i].days}><ChangeCell change={change} currency={a.currency} unitPrice/></td>)}<td>{money(a.cost, a.currency, 2)}</td><td><strong>{money(assetValue(a), currency, 2)}</strong></td><td className={color(p)}>{signed(p, a.currency)}<small>{a.cost === null ? 'Себестоимость неизвестна' : a.cost > 0 ? pct(p === null ? null : p / a.cost * 100) : 'Без затрат на покупку'}</small></td><td><button className="icon-button" aria-label={`Детали ${a.name}`} onClick={() => setSelected(a.id)}><ChevronRight size={17}/></button></td></tr>; })}</tbody></table></div> : <div className="asset-cards">{filtered.slice(0, limit).map(a => <button className="asset-card" key={a.id} onClick={() => setSelected(a.id)}><div className="asset-card-top"><AssetImage asset={a}/><span className={`asset-class-label ${a.class}`}>{classNames[a.class]}</span>{options[a.id]?.pinned && <Pin size={14}/>}</div><h3>{a.symbol || a.name}</h3><p>{a.symbol ? a.name : `${number(a.quantity)} шт. · ${a.category}`}</p><div className="asset-card-price">{money(assetValue(a), currency, 2)}<span className={color(knownPriceCost(a))}>{signed(knownPriceCost(a), a.currency)}</span></div><div className="card-price-change"><span>Цена за единицу · {money(a.price, a.currency, a.currency === 'USD' ? 6 : 2)}</span><div>{priceChanges.get(a.id)?.map((change, i) => <span key={horizons[i].days}><small>{horizons[i].label}</small><ChangeCell change={change} currency={a.currency} unitPrice/></span>)}</div></div><div className="asset-card-foot"><span>Куплено: {money(a.averageBuyPrice, a.currency, a.currency === 'USD' ? 5 : 2)}</span><ChevronRight size={16}/></div></button>)}</div>}
      {filtered.length > limit && <button className="load-more" onClick={() => setLimit(l => l + 24)}>Ещё {Math.min(24, filtered.length - limit)} из {filtered.length - limit}<ArrowRight size={16}/></button>}</> : <div className="table-scroll">{section === 'sandbox' && <p className="source-footnote">{transactions.filter(t => t.source === 'steam-csv').length} операций из CSV Steam. Остальные записи — учёт по вашей таблице; полная история покупок в CSV отсутствует.</p>}<table><thead><tr><th>Актив / операция</th><th>Дата</th><th>Количество</th><th>Цена</th><th>Сумма</th><th>Комиссия</th></tr></thead><tbody>{transactions.map(t => <tr key={`${t.asset.id}-${t.index}`}><td><button className="trade-name" onClick={() => setSelected(t.asset.id)}><span className={`trade-icon ${t.type}`}>{t.type === 'buy' ? <ArrowDownLeft size={16}/> : <ArrowUpRight size={16}/>}</span><span>{t.asset.symbol || t.asset.name}<small>{t.type === 'buy' ? 'Покупка' : t.type === 'sell' ? 'Продажа' : t.type}{tradeSource(t) ? ` · ${tradeSource(t)}` : ''}</small></span></button></td><td>{tradeDate(t)}</td><td>{number(t.quantity, 6)}</td><td>{money(t.unitPrice, t.currency, t.currency === 'USD' ? 6 : 2)}</td><td>{money(t.total, t.currency, 2)}</td><td>{feeText(t)}</td></tr>)}</tbody></table></div>}</section>
    <footer className="page-footer"><ShieldCheck size={14}/><span>Оценки Steam — до комиссии. Покупки крипты — в USD; эквивалент в ₽ по курсу оценки, не историческому курсу покупки.</span><span>Расписание котировок: 15 мин. · Проверка публикации: 5 мин.</span></footer>
    </div></main>
    {chosen && <div className="dialog-overlay" onMouseDown={e => { if (e.target === e.currentTarget) setSelected(null); }}><aside ref={dialogRef} className="asset-drawer" role="dialog" aria-modal="true" aria-label={chosen.name}><div className="drawer-top"><span>Детали актива</span><button ref={closeRef} className="icon-button" aria-label="Закрыть детали" onClick={() => setSelected(null)}><X size={20}/></button></div><div className="drawer-body"><AssetImage asset={chosen}/><span className={`asset-class-label ${chosen.class}`}>{classNames[chosen.class]}</span><h2>{chosen.name}</h2><p>{number(chosen.quantity, chosen.class === "crypto" ? 6 : 2)} {chosen.class === 'crypto' ? chosen.symbol : 'шт.'}</p><div className="drawer-value">{money(chosen.price === null ? null : chosen.price * chosen.quantity, chosen.currency, 2)}<small className={color(knownPriceCost(chosen))}>{signed(knownPriceCost(chosen), chosen.currency)} к покупке</small></div><div className="detail-metrics"><div><span>Средняя покупка</span><strong>{money(chosen.averageBuyPrice, chosen.currency, chosen.currency === 'USD' ? 6 : 2)}</strong></div><div><span>Рыночная цена</span><strong>{money(chosen.price, chosen.currency, chosen.currency === 'USD' ? 6 : 2)}</strong></div><div><span>Вложено</span><strong>{money(chosen.cost, chosen.currency, 2)}</strong></div><div><span>Источник / обновление</span><strong>{chosen.source}</strong><small>{time(chosen.updatedAt, true)}</small></div></div><a className="source-link" href={chosen.marketUrl} target="_blank" rel="noreferrer">Открыть источник <ExternalLink size={15}/></a>
    <h3>История цены за единицу</h3><HistoryChart snapshots={priceHistories.get(chosen.id) ?? []} currency={chosen.currency} title={`Цена ${chosen.name}`} unitPrice/>
    <h3><Target size={17}/> Личные настройки</h3><label className="field-label" htmlFor="target">Целевая цена, {chosen.currency}</label><input id="target" type="number" min="0" step="any" placeholder="Цена за единицу" value={chosenOptions.target ?? ''} onChange={e => updateOption({ target: e.target.value === '' ? undefined : Number(e.target.value) })}/><label className="field-label" htmlFor="note">Заметка</label><textarea id="note" rows={3} value={chosenOptions.note || ''} onChange={e => updateOption({ note: e.target.value })} placeholder="Комментарий по активу"/><button className="pin-button" onClick={() => updateOption({ pinned: !chosenOptions.pinned })}><Pin size={15}/>{chosenOptions.pinned ? 'Открепить' : 'Закрепить в начале'}</button><p className="local-note">Заметки и цели хранятся в этом браузере.</p><h3>Операции · {chosen.trades.length}</h3>{chosen.historyIncomplete && <p className="source-footnote">CSV содержит часть покупок. Остаток и средняя себестоимость сохранены по вашей таблице.</p>}{[...chosen.trades].sort(newestTradeFirst).map((t, i) => <div className="drawer-trade" key={i}><span className={`trade-icon ${t.type}`}><ArrowDownLeft size={16}/></span><div><strong>{t.type === 'buy' ? 'Покупка' : t.type === 'sell' ? 'Продажа' : t.type} · {number(t.quantity, 6)}</strong><small>{tradeSource(t) && `${tradeSource(t)} · `}{tradeDate(t)} · {money(t.unitPrice, t.currency, t.currency === 'USD' ? 6 : 2)} за ед.</small></div><strong>{money(t.total, t.currency, 2)}</strong></div>)}</div></aside></div>}
  </div>;
}
